[theme]
base="light"
primaryColor="#5D3A9B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
address = "0.0.0.0"

[ui]
hideTopBar = false

[client]
showErrorDetails = true