[theme]
base="light"
primaryColor="#5D3A9B"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false

[ui]
hideTopBar = true